// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-mxfp.cuh"

DECL_FATTN_MMA_MXFP_CASE(GGML_TYPE_MXFP4_E2M1, 64, 64, 16, 2);
DECL_FATTN_MMA_MXFP_CASE(GGML_TYPE_MXFP4_E2M1, 128, 128, 16, 2);
DECL_FATTN_MMA_MXFP_CASE(GGML_TYPE_MXFP4_E2M1, 256, 256, 16, 2);
DECL_FATTN_MMA_MXFP_CASE(GGML_TYPE_MXFP4_E2M1, 576, 512, 16, 2);
