// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-mxfp4.cuh"

DECL_FATTN_MMA_MXFP4_CASE(64, 64, 1, 8);
DECL_FATTN_MMA_MXFP4_CASE(128, 128, 1, 8);
DECL_FATTN_MMA_MXFP4_CASE(256, 256, 1, 8);
