// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-mxfp.cuh"

DECL_FATTN_MMA_MXFP_CASE(GGML_TYPE_MXFP8_E4M3, 64, 64, 1, 8);
DECL_FATTN_MMA_MXFP_CASE(GGML_TYPE_MXFP8_E4M3, 128, 128, 1, 8);
DECL_FATTN_MMA_MXFP_CASE(GGML_TYPE_MXFP8_E4M3, 256, 256, 1, 8);
DECL_FATTN_MMA_MXFP_CASE(GGML_TYPE_MXFP8_E4M3, 576, 512, 1, 8);
