// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-mxfp.cuh"

DECL_FATTN_MMA_MXFP_CASE(GGML_TYPE_MXFP4, 64, 64, 4, 4);
DECL_FATTN_MMA_MXFP_CASE(GGML_TYPE_MXFP4, 128, 128, 4, 4);
DECL_FATTN_MMA_MXFP_CASE(GGML_TYPE_MXFP4, 256, 256, 4, 4);
DECL_FATTN_MMA_MXFP_CASE(GGML_TYPE_MXFP4, 576, 512, 4, 4);
