// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-mxfp.cuh"

DECL_FATTN_MMA_MXFP_CASE(GGML_TYPE_MXFP8, 64, 64, 2, 4);
DECL_FATTN_MMA_MXFP_CASE(GGML_TYPE_MXFP8, 128, 128, 2, 4);
DECL_FATTN_MMA_MXFP_CASE(GGML_TYPE_MXFP8, 256, 256, 2, 4);
DECL_FATTN_MMA_MXFP_CASE(GGML_TYPE_MXFP8, 576, 512, 2, 4);
