// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_MXFP8_E4M3, GGML_TYPE_MXFP8_E4M3);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_MXFP8_E4M3, GGML_TYPE_MXFP8_E4M3);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_MXFP8_E4M3, GGML_TYPE_MXFP8_E4M3);
