// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-mxfp.cuh"

DECL_FATTN_MMA_MXFP_CASE(GGML_TYPE_MXFP8_E4M3, 64, 64, 8, 1);
DECL_FATTN_MMA_MXFP_CASE(GGML_TYPE_MXFP8_E4M3, 128, 128, 8, 1);
DECL_FATTN_MMA_MXFP_CASE(GGML_TYPE_MXFP8_E4M3, 256, 256, 8, 1);
DECL_FATTN_MMA_MXFP_CASE(GGML_TYPE_MXFP8_E4M3, 576, 512, 8, 1);
