// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-mxfp8.cuh"

DECL_FATTN_MMA_MXFP8_CASE(64, 64, 8, 2);
DECL_FATTN_MMA_MXFP8_CASE(128, 128, 8, 2);
DECL_FATTN_MMA_MXFP8_CASE(256, 256, 8, 2);
DECL_FATTN_MMA_MXFP8_CASE(576, 512, 8, 2);
