// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-mxfp.cuh"

DECL_FATTN_MMA_MXFP_CASE(GGML_TYPE_MXFP8, 64, 64, 4, 2);
DECL_FATTN_MMA_MXFP_CASE(GGML_TYPE_MXFP8, 128, 128, 4, 2);
DECL_FATTN_MMA_MXFP_CASE(GGML_TYPE_MXFP8, 256, 256, 4, 2);
DECL_FATTN_MMA_MXFP_CASE(GGML_TYPE_MXFP8, 576, 512, 4, 2);
