static constexpr __host__ __device__ ggml_cuda_mmq_config ggml_cuda_mmq_get_config_blackwell(ggml_type type, int J, bool fallback, ggml_prec s1) {
    if (type == GGML_TYPE_MXFP4) {
        // W4A8 (e4m3 activations) uses the FP8 SRAM layout, W4A4 the FP4 one
        CASE(GGML_TYPE_MXFP4, 256, 1, 128,   8, s1 == GGML_PREC_MXFP8 ? GGML_CUDA_MMQ_SRAM_LAYOUT_FP8 : GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, true);
        CASE(GGML_TYPE_MXFP4, 256, 1, 128,  16, s1 == GGML_PREC_MXFP8 ? GGML_CUDA_MMQ_SRAM_LAYOUT_FP8 : GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, true);
        CASE(GGML_TYPE_MXFP4, 256, 1, 128,  32, s1 == GGML_PREC_MXFP8 ? GGML_CUDA_MMQ_SRAM_LAYOUT_FP8 : GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, true);
        CASE(GGML_TYPE_MXFP4, 256, 1, 128,  64, s1 == GGML_PREC_MXFP8 ? GGML_CUDA_MMQ_SRAM_LAYOUT_FP8 : GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, true);
        CASE(GGML_TYPE_MXFP4, 256, 1, 128, 128, s1 == GGML_PREC_MXFP8 ? GGML_CUDA_MMQ_SRAM_LAYOUT_FP8 : GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, true);
        CASE(GGML_TYPE_MXFP4, 256, 1, 128,   8, s1 == GGML_PREC_MXFP8 ? GGML_CUDA_MMQ_SRAM_LAYOUT_FP8 : GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, false);
        CASE(GGML_TYPE_MXFP4, 256, 1, 128,  16, s1 == GGML_PREC_MXFP8 ? GGML_CUDA_MMQ_SRAM_LAYOUT_FP8 : GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, false);
        CASE(GGML_TYPE_MXFP4, 256, 1, 128,  24, s1 == GGML_PREC_MXFP8 ? GGML_CUDA_MMQ_SRAM_LAYOUT_FP8 : GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, false);
        CASE(GGML_TYPE_MXFP4, 256, 1, 128,  32, s1 == GGML_PREC_MXFP8 ? GGML_CUDA_MMQ_SRAM_LAYOUT_FP8 : GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, false);
        CASE(GGML_TYPE_MXFP4, 256, 1, 128,  40, s1 == GGML_PREC_MXFP8 ? GGML_CUDA_MMQ_SRAM_LAYOUT_FP8 : GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, false);
        CASE(GGML_TYPE_MXFP4, 256, 1, 128,  48, s1 == GGML_PREC_MXFP8 ? GGML_CUDA_MMQ_SRAM_LAYOUT_FP8 : GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, false);
        CASE(GGML_TYPE_MXFP4, 256, 1, 128,  64, s1 == GGML_PREC_MXFP8 ? GGML_CUDA_MMQ_SRAM_LAYOUT_FP8 : GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, false);
        CASE(GGML_TYPE_MXFP4, 256, 1, 128,  80, s1 == GGML_PREC_MXFP8 ? GGML_CUDA_MMQ_SRAM_LAYOUT_FP8 : GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, false);
        CASE(GGML_TYPE_MXFP4, 256, 1, 128,  96, s1 == GGML_PREC_MXFP8 ? GGML_CUDA_MMQ_SRAM_LAYOUT_FP8 : GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, false);
        CASE(GGML_TYPE_MXFP4, 256, 1, 128, 112, s1 == GGML_PREC_MXFP8 ? GGML_CUDA_MMQ_SRAM_LAYOUT_FP8 : GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, false);
        CASE(GGML_TYPE_MXFP4, 256, 1, 128, 128, s1 == GGML_PREC_MXFP8 ? GGML_CUDA_MMQ_SRAM_LAYOUT_FP8 : GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, false);
    }

    CASE(GGML_TYPE_NVFP4, 256, 1, 128,   8, GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, true);
    CASE(GGML_TYPE_NVFP4, 256, 1, 128,  16, GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, true);
    CASE(GGML_TYPE_NVFP4, 256, 1, 128,  32, GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, true);
    CASE(GGML_TYPE_NVFP4, 256, 1, 128,  64, GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, true);
    CASE(GGML_TYPE_NVFP4, 256, 1, 128, 128, GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, true);
    CASE(GGML_TYPE_NVFP4, 256, 1, 128,   8, GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, false);
    CASE(GGML_TYPE_NVFP4, 256, 1, 128,  16, GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, false);
    CASE(GGML_TYPE_NVFP4, 256, 1, 128,  24, GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, false);
    CASE(GGML_TYPE_NVFP4, 256, 1, 128,  32, GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, false);
    CASE(GGML_TYPE_NVFP4, 256, 1, 128,  40, GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, false);
    CASE(GGML_TYPE_NVFP4, 256, 1, 128,  48, GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, false);
    CASE(GGML_TYPE_NVFP4, 256, 1, 128,  64, GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, false);
    CASE(GGML_TYPE_NVFP4, 256, 1, 128,  80, GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, false);
    CASE(GGML_TYPE_NVFP4, 256, 1, 128,  96, GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, false);
    CASE(GGML_TYPE_NVFP4, 256, 1, 128, 112, GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, false);
    CASE(GGML_TYPE_NVFP4, 256, 1, 128, 128, GGML_CUDA_MMQ_SRAM_LAYOUT_FP4, MMQ_ITER_K_FP4, true, false);

    return ggml_cuda_mmq_get_config_ampere(type, J, fallback);
}
